### Ordinal Logistic Regression
Ordinal logistic regression (also called the **proportional odds model**) is a statistical method used when:

- The **dependent variable is ordinal**  
   (categories have a natural order)
- But the distances between categories are not assumed equal.

Examples:
| Problem               | Target Classes                             |
| --------------------- | ------------------------------------------ |
| Customer satisfaction | Poor < Average < Good < Excellent          |
| Movie rating          | 1 star < 2 star < 3 star < 4 star < 5 star |
| Disease severity      | Mild < Moderate < Severe                   |
| Education level       | High School < Bachelor < Master < PhD      |
| Risk assessment       | Low < Medium < High                        |


These classes are:

- **Categorical**
- **Discrete**
- **Ordered**

Traditional logistic regression cannot fully utilize this ordering.

##### Key Idea
Instead of predicting a continuous value, ordinal logistic regression predicts the probability that an observation falls into an ordered category.

It models:  
$
P(Y≤j)
$  
for each category threshold j.

### Why Binary or Multinomial Logistic Regression is Not Enough
#### Binary Logistic Regression
Works only for:
```
Y ∈ {0,1}
```
Cannot handle:
```
Y ∈ {1,2,3,4,5}
```

#### Multinomial Logistic Regression
Can handle multiple classes:
```
Y ∈ {1,2,3,4,5}
```
BUT:

It treats all classes as completely independent.

Example:

Class distances become:

- Poor <-> Excellent
- Poor <-> Average

Both treated similarly.

This is incorrect because:
```
Poor < Average < Good < Excellent
```
There is a natural ranking.


### What Ordinal Logistic Regression Does
Ordinal Logistic Regression models:

- categorical outputs
- with meaningful ordering

It learns:

> probability that outcome belongs to a category or below it

instead of directly predicting isolated classes.

### Core Idea
Instead of modeling:  
$
P(Y=k)
$  

Ordinal Logistic Regression models cumulative probabilities:  
$  
P(Y≤k)
$

Example:

For ratings:  
$
1<2<3<4<5
$

The model learns:  
$
P(Y≤1) 
$   
$
P(Y≤2)  
$  
$
P(Y≤3)
$  
$
P(Y≤4)  
$

### Real Intuition

Suppose salary influences satisfaction.

Higher salary -> higher satisfaction probability.

Instead of building 5 separate classifiers:

Ordinal Logistic Regression creates **ordered decision boundaries.**

Example:
| Boundary    | Meaning                      |
| ----------- | ---------------------------- |
| Threshold 1 | Poor vs Rest                 |
| Threshold 2 | Poor/Average vs Rest         |
| Threshold 3 | Up to Good vs Better         |
| Threshold 4 | Up to Very Good vs Excellent |

These thresholds preserve ordering.

### Mathematical Foundation
#### Assume Ordered Classes
```
Y ∈ {1,2,3,…,K}
```
Example:
```
Y ∈ {1,2,3,4,5}
```

### Cumulative Logit Model

The standard ordinal logistic regression model is:  
$
\log\left(\frac{P(Y \leq  k)}{P(Y >  k)}\right) = \theta_k - (\mathbf{w}^T \mathbf{x})
$

This is called the:

**Proportional Odds Model**


### Understanding Each Term
#### Left Side
$
\log\left(\frac{P(Y \leq  k)}{P(Y >  k)}\right)
$

This is the log-odds of being in category k or below.

#### Threshold Parameter
$
\theta_k
$

Different threshold for every boundary.

Example:
| Threshold  | Meaning                                 |
| ---------- | --------------------------------------- |
| $\theta_1$ | Boundary between class 1 and others     |
| $\theta_2$ | Boundary between classes 1-2 and others |
| $\theta_3$ | Boundary between classes 1-3 and others |

#### Linear Component
$
\mathbf{w}^T \mathbf{x}
$

Same as logistic regression:  
$
w_1x_1 + w_2x_2 + ... + w_nx_n
$

### Why Same Weights Are Used

Important property:

The same weight vector w is shared across all thresholds.

Only thresholds change.

This means:

Feature effects remain consistent across categories.

Example:

If salary increases satisfaction:

- it increases odds consistently
- across all category boundaries

This is called:

**Proportional Odds Assumption**

### Sigmoid Transformation
From:
$
\log\left(\frac{P(Y \leq  k)}{P(Y >  k)}\right) = \theta_k - (\mathbf{w}^T \mathbf{x})
$

Applying sigmoid:  
$
P(Y \leq k) = \frac{1}{1 + e^{-(\theta_k - \mathbf{w}^T \mathbf{x})}}
$

### Obtaining Exact Class Probabilities
Cumulative probabilities are converted into exact class probabilities.

Example:  
$
P(Y=1)=P(Y≤1)  \\
P(Y=2)=P(Y≤2)−P(Y≤1) \\
P(Y=3)=P(Y≤3)−P(Y≤2) \\
$

General form:  
$
P(Y=k) = P(Y≤k)−P(Y≤k−1)
$

### Visual Understanding

Imagine a number line:
```
----|---------|----------|----------|-----
   θ1        θ2         θ3         θ4
```

Each threshold separates ordered regions.

The model predicts where a sample lies.

### Example
Suppose:

Features:

- Salary
- Work-life balance
- Team culture

Target:
| Value | Satisfaction |
| ----- | ------------ |
| 1     | Poor         |
| 2     | Average      |
| 3     | Good         |
| 4     | Very Good    |
| 5     | Excellent    |

The model learns:

- thresholds between categories
- how features move probability toward higher/lower classes

### Training Objective

Like logistic regression, training uses:

#### Maximum Likelihood Estimation (MLE)

Goal:

Find:

- weights $w$
- thresholds $\theta_k$​

that maximize likelihood of observed labels.

Loss function becomes:  
$
L = - \sum_i \log P(Y = y_i \mid x_i)
$

Optimization usually done using:

- Gradient Descent
- L-BFGS
- Newton methods

### Important Assumption
##### Proportional Odds Assumption

Feature effects are constant across all category boundaries.

Meaning:

If a feature increases odds once,
it increases odds similarly everywhere.

##### Example

Salary effect:
| Boundary          | Effect   |
| ----------------- | -------- |
| Poor vs Better    | Positive |
| Average vs Better | Positive |
| Good vs Better    | Positive |

Same coefficient used.

### When This Assumption Fails

Sometimes feature impact differs across levels.

Example:

Education may strongly affect:

- Low -> Medium

but weakly affect:

- High -> Very High

Then proportional odds assumption breaks.

Alternative models are needed:

- Partial Proportional Odds Model
- Generalized Ordered Logit Model

### Advantages
| Advantage                     | Explanation                   |
| ----------------------------- | ----------------------------- |
| Uses ordering information     | Better than multinomial       |
| Fewer parameters              | Shared weights                |
| More interpretable            | Ordered thresholds            |
| Better statistical efficiency | Especially with small data    |
| Probabilistic output          | Class probabilities available |


### Disadvantages
| Limitation                                 | Explanation                   |
| ------------------------------------------ | ----------------------------- |
| Proportional odds assumption               | Often unrealistic             |
| Sensitive to imbalance                     | Rare classes problematic      |
| Linear boundaries                          | Cannot model complex patterns |
| Harder interpretation than binary logistic | Multiple thresholds involved  |


### Comparison with other Logistic Regressions
| Model                           | Output Type              | Ordered? |
| ------------------------------- | ------------------------ | -------- |
| Binary Logistic Regression      | 2 classes                | No       |
| Multinomial Logistic Regression | Multiple classes         | No       |
| Ordinal Logistic Regression     | Multiple ordered classes | Yes      |

### Real Industry Use Cases
##### Healthcare

Disease severity:

- Mild
- Moderate
- Severe
- Finance

##### Credit ratings:

- Low risk
- Medium risk
- High risk

### Example
#### Problem Statement
A telecom infrastructure platform receives thousands of operational incidents every day from:

- gNB logs
- UE traces
- Kubernetes clusters
- CI/CD build systems
- OAI runtime environments
- Network monitoring systems
- Alarm management systems

Each incident must be assigned a severity level:
| Severity Level | Meaning       |
| -------------- | ------------- |
| 1              | Informational |
| 2              | Minor         |
| 3              | Moderate      |
| 4              | Major         |
| 5              | Critical      |

The challenge:

- severity classes are ordered
- misclassification cost is unequal
- predicting "Minor" instead of "Critical" is extremely dangerous
- predicting "Major" instead of "Critical" is less harmful

Traditional multiclass classification fails to capture this ordering.

The objective:

> Predict incident severity using system logs, metrics, alarms, and runtime context while preserving ordinal relationships between severity levels.

This becomes an ideal Ordinal Logistic Regression problem.

#### Why This Is an Ordinal Problem

Severity levels are not independent categories.

There is natural ordering:
```
Informational < Minor < Moderate < Major < Critical
```
Distance matters.

Examples:
| True Severity | Prediction    | Impact                     |
| ------------- | ------------- | -------------------------- |
| Critical      | Major         | Acceptable degradation     |
| Critical      | Informational | Catastrophic failure       |
| Moderate      | Minor         | Small issue                |
| Moderate      | Critical      | Expensive false escalation |


In [13]:
import pandas as pd
import numpy as np
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error
)

from mord import LogisticIT

In [2]:
# Load Dataset
df = pd.read_csv("./data/telecom_incident_severity_dataset.csv")

df.head()

,incident_id,timestamp,service_name,region,deployment_environment,cpu_usage_percent,memory_usage_percent,packet_drop_rate_percent,latency_ms,error_count,restart_count,build_failure_count,crash_frequency_per_hour,alarm_density_per_minute,affected_services_count,active_users_impacted,severity_level,severity_label
0,INC-100000,2026-01-01 00:00:00,SMF,APAC,staging,69.92,59.51,3.29,19.86,10,3,2,0.20,0.81,3,15189,2,Minor
1,INC-100001,2026-01-01 00:01:00,gNB,EMEA,dev,33.69,67.66,0.86,93.40,19,2,1,0.07,11.89,3,0,2,Minor
2,INC-100002,2026-01-01 00:06:00,NSSF,APAC,prod,43.56,95.34,0.33,123.94,21,4,6,0.22,0.19,2,11944,2,Minor
3,INC-100003,2026-01-01 00:03:00,AMF,APAC,qa,46.94,81.03,0.82,16.50,19,3,4,0.44,0.49,3,13344,2,Minor
4,INC-100004,2026-01-01 00:04:00,NSSF,APAC,qa,31.45,40.47,3.27,370.26,15,6,0,0.11,0.13,4,14965,2,Minor


In [3]:
df.shape

(50000, 18)

In [4]:
# Feature Selection
features = [
    "cpu_usage_percent",
    "memory_usage_percent",
    "packet_drop_rate_percent",
    "latency_ms",
    "error_count",
    "restart_count",
    "build_failure_count",
    "crash_frequency_per_hour",
    "alarm_density_per_minute",
    "affected_services_count",
    "active_users_impacted"
]

X = df[features]
y = df["severity_level"]

In [5]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Shape: ", X_train.shape)
print("Testing Shape: ", X_test.shape)

Training Shape:  (40000, 11)
Testing Shape:  (10000, 11)


In [6]:
# Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
# Model Training
model = LogisticIT()
model.fit(X_train_scaled, y_train)

,alpha,1.0
,verbose,0
,max_iter,1000


In [9]:
# Predictions
y_pred = model.predict(X_test_scaled)

In [10]:
# Evaluation
accuracy = accuracy_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("Model Performance:")
print(f"\nAccuracy: {accuracy:.4f}")
print(f"\nMean Absolute Error: {mae:.4f}")
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Model Performance:

Accuracy: 0.9994

Mean Absolute Error: 0.0006

Classification Report:

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1634
           2       1.00      1.00      1.00      7037
           3       1.00      1.00      1.00      1314
           4       1.00      1.00      1.00        15

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000


Confusion Matrix:

[[1629    5    0    0]
 [   0 7037    0    0]
 [   0    1 1313    0]
 [   0    0    0   15]]


In [12]:
print("Model Coefficients:")

for feature, coef in zip(features, model.coef_):
    print(f"{feature}: {coef:.4f}")

print("\nThresholds:")
print(model.theta_)

Model Coefficients:
cpu_usage_percent: 2.8318
memory_usage_percent: 1.7298
packet_drop_rate_percent: 20.6265
latency_ms: 4.6983
error_count: 0.9368
restart_count: 4.9464
build_failure_count: 6.0869
crash_frequency_per_hour: 12.1161
alarm_density_per_minute: 14.8703
affected_services_count: 12.2823
active_users_impacted: 1.8902

Thresholds:
[-30.44784436  35.37036478 133.73788693]


In [15]:
MODEL_DIR = "project-ordinal_logistic_regression"

os.makedirs(MODEL_DIR, exist_ok=True)

# Save Model
model_path = os.path.join(
    MODEL_DIR,
    "severity_model.pkl"
)

scaler_path = os.path.join(
    MODEL_DIR,
    "scaler.pkl"
)

joblib.dump(model, model_path)

joblib.dump(scaler, scaler_path)

print("\nModel and scaler saved successfully.")


Model and scaler saved successfully.
