Support Vector Machine (SVM) is a supervised machine learning algorithm used for:

1. Classification
1. Regression
1. Outlier/Anomaly Detection

SVM is one of the most mathematically elegant machine learning algorithms because it transforms a prediction problem into an optimization problem.

The primary objective is:
> Find the optimal decision boundary that maximizes separation between classes.

Unlike Logistic Regression, which focuses on probability estimation, SVM focuses on finding the best possible boundary with the largest safety margin.

### Inutition
Consider a binary classification problem:
| Age | Income | Purchased |
| --- | ------ | --------- |
| 25  | 30000  | No        |
| 45  | 80000  | Yes       |
| 35  | 50000  | No        |
| 55  | 120000 | Yes       |

A line can separate "Yes" and "No" customers.

Many separating lines may exist.

SVM asks:
> Which separating line is the best?

Answer:
> The line that leaves the maximum distance from both classes.

This distance is called the **Margin**.

### Hyperplane
The decision boundary in SVM is called a Hyperplane.
#### 2D
A line

$
w_1x_1 + w_2x_2 + b = 0
$

#### 3D
A plane

##### n-Dimensions
A hyperplane

$
w^Tx + b = 0
$

Where:
- $w$ = weights
- $x$ = features
- $b$ = bias

### Classification Rule
For a new sample:

$
f(x) = w^Tx + b
$

If 

$
f(x) > 0
$

Class = +1

If 

$
f(x) < 0
$

Class = -1

### Margin
The margin is the distance between:
- Hyperplane
- Closest positive samples
- Closest negative samples

Example:
```
Class A      Margin      Hyperplane      Margin      Class B

   ● ● ●       |             |              |          ▲ ▲ ▲
```

Small Margin:
- Tiny change in new data may cause misclassification.

Larger margin:
- Better generalization
- Less overfitting
- Better robustness

### Support Vectors
The points closest to the decision boundary are called Support Vectors.

Example:
```
● ● ● ●

    ●      <- support vector

------------

         ▲ <- support vector

▲ ▲ ▲ ▲
```

Only these points determine the hyperplane.

Removing far-away points often does not change the model.

This is why the algorithm is called: **Support Vector Machine**

### Why Support Vectors Matter

Assume 10,000 points exist.

Only 30 points lie near the boundary.

The optimal hyperplane is determined entirely by those 30 points.

This makes SVM mathematically efficient.

### Maximum Margin Principle
Among all possible separating hyperplanes:

Choose:
$$
Maximum Margin Hyperplane
$$

Mathematically:  
Margin

$$
\frac{2}{\lVert w \rVert}
$$

Maximizing the margin means:

$$
\max \frac{2}{\lVert w \rVert}
$$

Since the factor 2 is constant, this is equivalent to:

$$
\max \frac{1}{\lVert w \rVert}
$$

which is equivalent to:

$$
\min \lVert w \rVert
$$

and, for mathematical convenience:

$$
\min \frac{1}{2}\lVert w \rVert^2
$$

This becomes the optimization objective in a hard-margin SVM.

### Hard-Margin SVM
Used when the data is perfectly separable.

Constraint
For every training sample:

$$
y_i \left( w^T x_i + b \right) \geq 1,
\quad \forall i
$$

Optimization:

$$
\min_{w,b} \frac{1}{2}\lVert w \rVert^2
$$

subject to:

$$
y_i \left( w^T x_i + b \right) \geq 1,
\quad \forall i
$$

### Problem

Real-world datasets rarely have perfect separation.

Examples:
- Fraud Detection
- Customer Churn
- Medical Diagnosis

Usually classes overlap.

Hard Margin fails.

### Soft Margin SVM

Most production systems use Soft Margin SVM.

It allows some classification errors by introducing **slack variables**:

$$
\xi_i
$$

The constraint becomes:

$$
y_i \left( w^T x_i + b \right) \geq 1 - \xi_i
$$

where

$$
\xi_i \geq 0
$$

#### Optimization Objective

$$
\min_{w,b,\xi}
\frac{1}{2}\lVert w \rVert^2
+
C \sum_{i=1}^{n} \xi_i
$$

subject to:

$$
y_i \left( w^T x_i + b \right) \geq 1 - \xi_i,
\quad \forall i
$$

$$
\xi_i \geq 0,
\quad \forall i
$$

### Regularization Parameter (C)
One of the most important hyperparameters.
$$
C
$$
controls:

##### Margin vs Error Tradeoff

**Large C**
```
C = 100
```
Punishes errors heavily.

Characteristics:

- Narrow margin
- Lower bias
- Higher variance
- Overfitting risk

**Small C**
```
C = 0.01
```
Allows more violations.

Characteristics:

- Wider margin
- Higher bias
- Lower variance
- Better generalization

Example:
| C Value | Behavior              |
| ------- | --------------------- |
| 0.01    | Very soft margin      |
| 0.1     | Soft margin           |
| 1       | Default               |
| 10      | Strict classification |
| 100     | Very strict           |

#### Geometric Interpretation
Large C:
```
Trying to classify every point correctly
```
Small C:
```
Allows few errors
Focuses on wider margin
```

### Linear SVM

Works when classes are linearly separable.

Decision boundary:

$
w^Tx + b = 0
$

Example datasets:

- Spam Detection
- Text Classification
- Document Categorization

Text data often becomes linearly separable in high dimensions.

### Non-Linear Problems
Consider:
```
Inner Circle = Class A
Outer Ring = Class B
```
No straight line can separate them.

Linear SVM fails.

### Feature Transformation
Map data into a higher dimension.

Example:  
Original feature:
$$
x
$$
Transform:
$$
(x,x^2)
$$
A non-linear problem can become linearly separable.

### Kernel Trick
The **Kernel Trick** is a technique used in **Support Vector Machines (SVMs)** to handle data that is **not linearly separable** in its original feature space.

Instead of explicitly transforming the data into a higher-dimensional space, the kernel trick computes the **inner products** in that higher-dimensional space directly, making the computation much more efficient.

#### The need for Kernel Trick
Consider a dataset like this:
```
○ ○ ○
○ ● ○
○ ○ ○
```
The classes cannot be separated by a straight line in 2D.

However, if the data is transformed into a higher-dimensional space, the classes may become linearly separable.

For example:
$$
(x_1, x_2) → (x_1, x_2, x_1^2, x_2^2)
$$

In the new space, a hyperplane can separate the classes.

#### The Key Idea
Instead of computing the transformation
$$
ϕ(x)
$$
explicitly, SVM uses a **kernel function**:
$$
K(x_i, x_j) = ϕ(x_i)^T ϕ(x_j)
$$
which directly computes the dot product in the transformed feature space.

This avoids the expensive computation of creating high-dimensional features.

#### Common Kernels
##### 1. Linear Kernel
No Transformation is applied.
$$
K(x_i, x_j) = x_i^Tx_j
$$
Used when the data is approximately linearly separable.

##### 2. Polynomial Kernel
Creates polynomial decision boundaries.
$$
K(x_i, x_j) = (x_i^Tx_j + c)^d
$$

where:
- $d$ = degree of the polynomial
- $c$ = constant term

##### 3. RBF (Gaussian) Kernel
The most commonly used kernel in practice.
$$
k(x_i, x_j) = exp(-γ||x_i - x_j||^2)
$$

where:
- $γ$ controls the influence of each training point
- This kernel can model highly non-linear relationships.

##### 4. Sigmoid Kernel
Inspired by neural networks.
$$
k(x_i, x_j) = tanh(αx_i^Tx_j + c)
$$

##### Mathematical Intuition
Without kernels:
$$
SVM works on ϕ(x)
$$

and computes
$$
ϕ(x_i)^Tϕ(x_j) 
$$	​
directly.

With the kernel trick:
$$
ϕ(x_i)^Tϕ(x_j) = K(x_i, x_j)
$$

so we never need to compute $ϕ(x)$ explicitly.

### Gamma Parameter (γ)

Used in RBF kernel.

Controls influence of a point.

**Small Gamma**
- Far points influence each other.
- Smooth boundary.
- Higher bias.

Smooth Curve

**Large Gamma**
- Only nearby points matter.
- Highly complex boundary.
- Overfitting risk.

Highly Wiggly Curve

### Understanding C and Gamma Together
Most tuning effort focuses here.
| Gamma | C    | Result       |
| ----- | ---- | ------------ |
| Low   | Low  | Underfit     |
| Low   | High | Moderate     |
| High  | Low  | Complex      |
| High  | High | Overfit Risk |

### Choosing Kernels
| Dataset                      | Kernel     |
| ---------------------------- | ---------- |
| Text                         | Linear     |
| High Dimensional Sparse Data | Linear     |
| Nonlinear Medium Dataset     | RBF        |
| Feature Interactions Needed  | Polynomial |
| Complex Boundaries           | RBF        |

### SVM for Regression (SVR)
Support Vector Regression.

Instead of classifying:

Predict continuous values.

Examples:
- House Price
- Stock Demand
- Sales Forecasting

### SVR Concept
Creates a tolerance band:
$$
ϵ
$$
```
     Upper Bound

================

Prediction Line

================

     Lower Bound
```
Errors inside band are ignored.

Optimization:

Find flattest function while keeping predictions within $ε$.

### Multiclass Classification
Original SVM:

Binary only.

Production systems use:

#### One-vs-Rest (OvR)
For 5 classes:

Train 5 classifiers.

Each classifier:
```
Class A vs Others
```
Prediction:

Highest score wins.

#### One-vs-One (OvO)
For K classes:
$$
K(K−1)/2	​
$$
models.

Example:

10 classes
$$
45
$$
models.

Often used internally in libraries.

### Computational Complexity
Training complexity approximately:
$$
O(n^2)
$$
to
$$
O(n^3)
$$
depending on solver.

Memory:
$$
O(n^2)
$$
Implications:

**Good**  
Small to Medium datasets

**Poor**  
Millions of rows

### Feature Scaling
Extremely important.

SVM relies on distances.

Without scaling:
| Feature | Value  |
| ------- | ------ |
| Age     | 20     |
| Income  | 500000 |

Income dominates

Perform **Standardization** or **Min-Max Scaling**.

### Outlier Sensitivity
SVM can be sensitive to outliers.

Example:
```
● ● ● ● ●

     X  <- Outlier

▲ ▲ ▲ ▲ ▲
```
Boundary may shift.

Solutions:
- Soft Margin
- Smaller C
- Outlier Removal

### Advantages
#### Effective in High Dimensions

Text classification may have:

100,000+ features

SVM handles it well.

#### Strong Theoretical Foundation

Optimization guarantees.

#### Robust Generalization

Maximum-margin principle.

#### Works Well with Small Datasets

Often better than deep learning.

#### Flexible via Kernels

Handles nonlinear data.

### Disadvantages
#### Expensive Training

Large datasets become slow.

#### Hyperparameter Sensitive

C and Gamma strongly affect performance.

#### Less Interpretable

Compared to Decision Trees.

#### Scaling Required

Performance degrades without normalization.

### Problem Statement
A large IT services company manages infrastructure for hundreds of enterprise customers.

Every day, thousands of incidents are raised through monitoring systems, ticketing tools, email alerts, and customer support channels.

Examples:
| Incident ID | Incident Description                        |
| ----------- | ------------------------------------------- |
| INC001      | Database server CPU utilization reached 98% |
| INC002      | Customer unable to login to portal          |
| INC003      | Payment gateway service unavailable         |
| INC004      | SSL certificate expiring in 5 days          |
| INC005      | Disk usage reached 75%                      |

The Service Desk team must manually determine the severity of each incident.

Severity Levels:
| Severity      | Meaning                     |
| ------------- | --------------------------- |
| Critical      | Major business outage       |
| High          | Significant impact          |
| Medium        | Partial service degradation |
| Low           | Minor issue                 |
| Informational | No immediate action needed  |

#### Business Objective
Build an AI-powered classification system that automatically predicts incident severity immediately after ticket creation.

Input:
```
Incident Title
Incident Description
Affected Service
Number of Users Impacted
Business Impact
System Metrics
```
Output:
```json
{
    "severity": "Critical"
}
```
The prediction should happen within milliseconds.

#### Why SVM Is Suitable
Incident data has several characteristics:

##### High-Dimensional Text Features
After TF-IDF transformation:
```
10,000+
20,000+
50,000+
```
features may exist.

Example:
```
database
latency
payment
gateway
timeout
cpu
memory
authentication
```
Each becomes a feature.

SVM performs exceptionally well in high-dimensional spaces.

##### Sparse Data
Typical ticket:
```
"Database connection timeout"
```
Only a few words appear.

Most features become:
```
0
```
Sparse matrices are ideal for Linear SVM.

##### Medium-Sized Datasets
Historical incidents:
```
50,000
100,000
200,000
```
records.

SVM handles such datasets effectively.

##### Clear Decision Boundaries
Words strongly indicate severity.

Examples:

Critical indicators:
```
outage
unavailable
crash
down
payment failure
authentication failure
```
Low severity indicators:
```
warning
certificate expiry
capacity planning
report generation
```
SVM can create highly effective separating hyperplanes.



In [1]:
import os
import joblib
import pandas as pd

from scipy.sparse import hstack
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

In [2]:
ARTIFACT_DIR = "project-support_vector_machine_classifier"

os.makedirs(
    ARTIFACT_DIR,
    exist_ok=True
)

In [3]:
df = pd.read_csv(
    "./data/incident_severity_dataset.csv"
)

print(f"Dataset Shape: {df.shape}")
df.head()

Dataset Shape: (50000, 5)


,incident_title,affected_users,cpu_usage,error_rate,severity
0,Memory usage elevated,877,52,8,Low
1,Disk usage warning,188,56,9,Low
2,Memory usage elevated,1572,55,1,Low
3,Intermittent connection issues,4022,60,28,Medium
4,CPU threshold warning,1645,56,4,Low


In [4]:
# Features
TEXT_COLUMN = "incident_title"

NUMERIC_COLUMNS = [
    "affected_users",
    "cpu_usage",
    "error_rate"
]

TARGET_COLUMN = "severity"

In [5]:
# Label Encoding
label_encoder = LabelEncoder()

y = label_encoder.fit_transform(
    df[TARGET_COLUMN]
)

In [6]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    df,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [7]:
# TF-IDF
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    stop_words="english"
)

X_train_text = tfidf.fit_transform(
    X_train[TEXT_COLUMN]
)

X_test_text = tfidf.transform(
    X_test[TEXT_COLUMN]
)

In [8]:
# Numerical Features
scaler = StandardScaler()

X_train_num = scaler.fit_transform(
    X_train[NUMERIC_COLUMNS]
)

X_test_num = scaler.transform(
    X_test[NUMERIC_COLUMNS]
)

In [9]:
# Combine Features
X_train_final = hstack(
    [
        X_train_text,
        X_train_num
    ]
)

X_test_final = hstack(
    [
        X_test_text,
        X_test_num
    ]
)

print(
    f"Final Feature Size: {X_train_final.shape}"
)

Final Feature Size: (40000, 99)


In [10]:
# Model
model = LinearSVC(
    C=1.0,
    random_state=42,
    max_iter=10000
)

In [11]:
# Training
model.fit(
    X_train_final,
    y_train
)

,"penalty penalty: {'l1', 'l2'}, default='l2'Specifies the norm used in the penalization. The 'l2'penalty is the standard used in SVC. The 'l1' leads to ``coef_``vectors that are sparse.",'l2'
,"loss loss: {'hinge', 'squared_hinge'}, default='squared_hinge'Specifies the loss function. 'hinge' is the standard SVM loss(used e.g. by the SVC class) while 'squared_hinge' is thesquare of the hinge loss. The combination of ``penalty='l1'``and ``loss='hinge'`` is not supported.",'squared_hinge'
,"dual dual: ""auto"" or bool, default=""auto""Select the algorithm to either solve the dual or primaloptimization problem. Prefer dual=False when n_samples > n_features.`dual=""auto""` will choose the value of the parameter automatically,based on the values of `n_samples`, `n_features`, `loss`, `multi_class`and `penalty`. If `n_samples` < `n_features` and optimizer supportschosen `loss`, `multi_class` and `penalty`, then dual will be set to True,otherwise it will be set to False... versionchanged:: 1.3 The `""auto""` option is added in version 1.3 and will be the default in version 1.5.",'auto'
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.For an intuitive visualization of the effects of scalingthe regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"multi_class multi_class: {'ovr', 'crammer_singer'}, default='ovr'Determines the multi-class strategy if `y` contains more thantwo classes.``""ovr""`` trains n_classes one-vs-rest classifiers, while``""crammer_singer""`` optimizes a joint objective over all classes.While `crammer_singer` is interesting from a theoretical perspectiveas it is consistent, it is seldom used in practice as it rarely leadsto better accuracy and is more expensive to compute.If ``""crammer_singer""`` is chosen, the options loss, penalty and dualwill be ignored.",'ovr'
,"fit_intercept fit_intercept: bool, default=TrueWhether or not to fit an intercept. If set to True, the feature vectoris extended to include an intercept term: `[x_1, ..., x_n, 1]`, where1 corresponds to the intercept. If set to False, no intercept will beused in calculations (i.e. data is expected to be already centered).",True
,"intercept_scaling intercept_scaling: float, default=1.0When `fit_intercept` is True, the instance vector x becomes ``[x_1,..., x_n, intercept_scaling]``, i.e. a ""synthetic"" feature with aconstant value equal to `intercept_scaling` is appended to the instancevector. The intercept becomes intercept_scaling * synthetic featureweight. Note that liblinear internally penalizes the intercept,treating it like any other term in the feature vector. To reduce theimpact of the regularization on the intercept, the `intercept_scaling`parameter can be set to a value greater than 1; the higher the value of`intercept_scaling`, the lower the impact of regularization on it.Then, the weights become `[w_x_1, ..., w_x_n,w_intercept*intercept_scaling]`, where `w_x_1, ..., w_x_n` representthe feature weights and the intercept weight is scaled by`intercept_scaling`. This scaling allows the intercept term to have adifferent regularization behavior compared to the other features.",1
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to ``class_weight[i]*C`` forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: int, default=0Enable verbose output. Note that this setting takes advantage of aper-process runtime setting in liblinear that, if enabled, may not workproperly in a multithreaded context.",0
,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo rand

In [12]:
# Prediction
predictions = model.predict(
    X_test_final
)

In [13]:
# Evaluation
accuracy = accuracy_score(
    y_test,
    predictions
)

print("\nAccuracy")
print(accuracy)

print("\nClassification Report")

print(
    classification_report(
        y_test,
        predictions,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix")

print(
    confusion_matrix(
        y_test,
        predictions
    )
)


Accuracy
1.0

Classification Report
               precision    recall  f1-score   support

     Critical       1.00      1.00      1.00      1208
         High       1.00      1.00      1.00      1765
Informational       1.00      1.00      1.00      1791
          Low       1.00      1.00      1.00      2417
       Medium       1.00      1.00      1.00      2819

     accuracy                           1.00     10000
    macro avg       1.00      1.00      1.00     10000
 weighted avg       1.00      1.00      1.00     10000


Confusion Matrix
[[1208    0    0    0    0]
 [   0 1765    0    0    0]
 [   0    0 1791    0    0]
 [   0    0    0 2417    0]
 [   0    0    0    0 2819]]


In [14]:
joblib.dump(
    model,
    f"{ARTIFACT_DIR}/svm_model.pkl"
)

joblib.dump(
    tfidf,
    f"{ARTIFACT_DIR}/tfidf_vectorizer.pkl"
)

joblib.dump(
    scaler,
    f"{ARTIFACT_DIR}/scaler.pkl"
)

joblib.dump(
    label_encoder,
    f"{ARTIFACT_DIR}/label_encoder.pkl"
)

['project-support_vector_machine_classifier/label_encoder.pkl']