### What is PyTorch?
#### Definition
PyTorch is an open-source Deep Learning framework developed by Meta.

It provides:
* Tensors
* Automatic Differentiation
* Neural Network APIs
* GPU Support
* Model Deployment


### NumPy vs PyTorch
Think of PyTorch as:
```
NumPy
  +
Automatic Gradients
  +
GPU Support
  +
Deep Learning Utilities
```

#### NumPy

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


#### PyTorch

In [2]:
import torch

tensor = torch.tensor([1, 2, 3])

print(tensor)

tensor([1, 2, 3])


Very similar.

### What is a Tensor?
#### Definition
A Tensor is the fundamental data structure in PyTorch.

Think:
```
Scalar → Vector → Matrix → Tensor
```

### Tensor Hierarchy
#### 0D Tensor (Scalar)



In [3]:
x = torch.tensor(5)

Shape:

In [4]:
torch.Size([])

torch.Size([])

#### 1D Tensor (Vector)

In [6]:
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


Shape:

In [7]:
torch.Size([3])

torch.Size([3])

#### 2D Tensor (Matrix)

In [8]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x)

tensor([[1, 2],
        [3, 4]])


Shape:

In [9]:
torch.Size([2,2])

torch.Size([2, 2])

#### 3D Tensor

In [10]:
x = torch.rand(3, 4, 5)
print(x)

tensor([[[0.6953, 0.6201, 0.1161, 0.8023, 0.2859],
         [0.5955, 0.8030, 0.5627, 0.8728, 0.4100],
         [0.4418, 0.8566, 0.8778, 0.8395, 0.8070],
         [0.5122, 0.9363, 0.2946, 0.9362, 0.6332]],

        [[0.6320, 0.9197, 0.9553, 0.9251, 0.1486],
         [0.1093, 0.0673, 0.4079, 0.6076, 0.8111],
         [0.9543, 0.3032, 0.8262, 0.6826, 0.8264],
         [0.6271, 0.3809, 0.1561, 0.3225, 0.5193]],

        [[0.6847, 0.0396, 0.0220, 0.2701, 0.4124],
         [0.0214, 0.6521, 0.0849, 0.8472, 0.4863],
         [0.2755, 0.9565, 0.8000, 0.8221, 0.7382],
         [0.3163, 0.3775, 0.6727, 0.3616, 0.2933]]])


Shape:
```
3 × 4 × 5
```
Often used for batches of data.

### Why Tensors Matter
Everything in Deep Learning is stored as tensors:
```
Input Data
Weights
Biases
Activations
Gradients
Predictions
```
Even GPT models internally operate on tensors.

### Creating Tensors
#### From Python List


In [11]:
import torch

x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


#### Zeros

In [12]:
x = torch.zeros(3, 4)

print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


#### Ones

In [13]:
x = torch.ones(2, 3)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### Random Values

In [14]:
x = torch.rand(2, 3)

print(x)

tensor([[0.1037, 0.5068, 0.8199],
        [0.9811, 0.6442, 0.8914]])


### Tensor Shapes

In [15]:
x = torch.rand(4, 5)

print(x.shape)

torch.Size([4, 5])


Meaning:
```
4 Rows
5 Columns
```

### Why Shapes Matter
Neural Networks perform:
```
Matrix Multiplication
```

which requires compatible shapes.

Example:
```
(32,100)
      ×
(100,50)
      ↓
(32,50)
```

Shape debugging is a daily Deep Learning task.

### Basic Tensor Operations
#### Addition

In [16]:
a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

print(a + b)

tensor([5, 7, 9])


#### Multiplication

In [17]:
print(a * b)

tensor([ 4, 10, 18])


#### Matrix Multiplication

In [18]:
A = torch.rand(2,3)

B = torch.rand(3,4)

C = torch.matmul(A, B)

print(C.shape)

torch.Size([2, 4])


### Tensor Reshaping
Often needed during model building.

#### Reshape

In [19]:
x = torch.arange(12)

x = x.reshape(3,4)

print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


#### Broadcasting
One of PyTorch's most useful features.

In [20]:
A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([10,20])

print(A + B)

tensor([[11, 22],
        [13, 24]])


PyTorch automatically expands:
```
[10,20]

to

[10,20]
[10,20]
```

This is called: **Broadcasting**

### CPU vs GPU
#### CPU
* General Purpose
* Slower for DL

#### GPU
* Massively Parallel
* Much Faster

#### Diagram
```
CPU

Task
 ↓
Task
 ↓
Task
 ↓
Task
```
```
GPU

Task Task Task Task
Task Task Task Task
Task Task Task Task
```

### Move Tensor to GPU
```python
device = "cuda"

x = torch.tensor(
    [1,2,3]
).to(device)
```

#### Check Device
```python
print(x.device)
```

Output:
```
cuda:0
```

or
```
cpu
```

### Common Tensor Functions
#### Mean
```python
x.mean()
```

#### Sum
```python
x.sum()
```

#### Maximum
```python
x.max()
```

#### Minimum
```python
x.min()
```

### Typical Deep Learning Flow
```
Dataset
   ↓
Tensor
   ↓
Neural Network
   ↓
Tensor
   ↓
Loss
   ↓
Tensor
   ↓
Gradient
```

Deep Learning is essentially:
```
Large Tensor Computation
```