### NumPy (Numerical Python) is:
- a **high-performance numerical computing library**
- built around a multi-dimensional array type called `ndarray`
- written in C and optimized for vectorized computing

Everything in NumPy revolves around ndarray:
A **fixed-size, homogeneous** (same dtype), **N-dimensional** array.

Internally it stores:
- Pointer to memory
- Shape (dimensions)
- Strides (how to move to next element)
- dtype (data type)

In [38]:
import numpy as np

In [39]:
a = np.array([1, 2, 3])

print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim) 


[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


#### Array Attributes

In [40]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

print(arr.ndim) # number of dimensions
print(arr.shape) # rows, columns
print(arr.size) # total elements
print(arr.dtype) # data type
print(arr.itemsize) # bytes per element
print(arr.nbytes) # total bytes = itemsize * size

2
(2, 3)
6
int64
8
48


### Array Creation Methods

#### 1. np.array()
Convert Python list -> ndarray

In [41]:
np.array([1, 2, 3])
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

#### 2. np.arange(start, stop, step)
Like range(), but returns ndarray

In [42]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### 3. np.linspace(start, end, num)
Evenly spaced values

In [43]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

#### 4. Zeros/Ones/Full

In [44]:
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


#### 5. Identity Matrix

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 6. Empty Array
Creates array **without initializing memory** → very fast

Contains garbage values

In [46]:
np.empty((3, 2))

array([[2.5e-323, 2.5e-323],
       [2.5e-323, 2.5e-323],
       [2.5e-323, 2.5e-323]])

### Exercise 1
Create a 3×3 array of numbers from 1 to 9.

In [47]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 2
Create:
- a zero matrix of shape (2, 4)
- a ones vector of length 5
- a full matrix of shape (3, 3) filled with 7

In [49]:
zero_matrix = np.zeros((2, 4))
print(zero_matrix)
ones_vector = np.ones(5)
print(ones_vector)
matrix_7 = np.full((3, 3), 7)
print(matrix_7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Exercise 3
Print all attributes:
- shape
- dtype
- size
- nbytes

for array np.linspace(0, 10, 15)

In [36]:
arr = np.linspace(0, 10, 15)
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.nbytes)

(15,)
float64
15
120


### Exercise 4
Create an array from 10 to 20 with step size 2 using `arange`.

In [50]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])