### Basic Indexing

#### 1D Array:

In [2]:
import numpy as np

In [3]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])

10
50


#### 2D Array:

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 0]) # b[0][0]
print(b[1, 2]) #b[1][2]

1
6


### Slicing
#### Syntax:
array[start : stop : step]

In [5]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[1:4])
print(a[:3])
print(a[3:])
print(a[::-1])

[1 2 3]
[0 1 2]
[3 4 5]
[5 4 3 2 1 0]


#### 2D Slicing:
array[row_slice, column_slice]

In [6]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b[:2, 1:]  

array([[2, 3],
       [5, 6]])

### Views and Copies
**Slicing creates a view, NOT a copy**
- No new memory is allocated.
- The slice refers to the same data as the original


In [7]:
a = np.array([10, 20, 30, 40, 50])
s = a[1:4]
s[:] = 999
print(a)

[ 10 999 999 999  50]


**Slicing = view**

**Fancy indexing = copy**

### Boolean Indexing (Filtering)

In [9]:
a = np.array([10, 15, 20, 25, 30])
mask = a > 20
print(mask)

result = a[a > 20]
print(result)

[False False False  True  True]
[25 30]


In [11]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

result = b[b % 2 == 0]
print(result)

[2 4 6 8]


### Fancy (Integer) Indexing
Fancy indexing = using a list/array of indices.

In [12]:
a = np.array([10, 20, 30 , 40, 50])
idx = [0, 2, 4]
a[idx]

array([10, 30, 50])

Fancy Indexing **ALWAYS** creates a copy

In [13]:
b = a[[1, 3]]
b[:] = 999
print(a)

[10 20 30 40 50]


In [15]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
b[[0,1,2], [1,2,3]]

array([ 1,  6, 11])

| Operation                     | View or Copy?      |
| ----------------------------- | ------------------ |
| Basic slicing (`a[1:5]`)      | **View**           |
| Slicing a 2D array            | **View**           |
| Boolean indexing              | **Copy**           |
| Fancy indexing (`a[[1,3,5]]`) | **Copy**           |
| Mixing fancy + slicing        | **Copy**           |
| Reshape (usually)             | **View**           |
| ravel()                       | View when possible |
| flatten()                     | **Copy**           |


### Exercise 1
a = np.array([10, 20, 30, 40, 50])
Create a slice s that contains [20, 30, 40] and modify s[:] = 0.
What does a become?

In [30]:
a = np.array([10, 20, 30, 40, 50])
s = a[1:4]
s[:] = 0
print(a)

[10  0  0  0 50]


### Exercise 2
**Given:**
b = np.arange(12).reshape(3,4)

**Extract:**
[[1, 2],
 [5, 6]]



In [26]:
b = np.arange(12).reshape(3,4)
print(b)
print(b[:2, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]


### Exercise 3
Using boolean indexing, from this array:

c = np.array([5, -2, 10, -4, 7])

Replace all negative numbers with 0

In [28]:
c = np.array([5, -2, 10, -4, 7])
c[c < 0] = 0
print(c)

[ 5  0 10  0  7]


### Exercise 4
Using fancy indexing:

a = np.array([10, 20, 30, 40, 50])

Pick elements at indices `[0, 3, 4]`

In [31]:
a = np.array([10, 20, 30, 40, 50])
idx = [0, 3, 4]
a[idx]

array([10, 40, 50])