In [1]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)

int64


**Why dtype matters:**
- Memory: `float32` = 4 bytes, `float64` = 8 bytes
- Speed: smaller types → better cache usage
- Correctness: integers cannot represent `NaN`
- ML compatibility: GPUs prefer float32

| Category | Examples                          |
| -------- | --------------------------------- |
| Integers | `int8`, `int16`, `int32`, `int64` |
| Unsigned | `uint8`, `uint16`, `uint32`       |
| Floats   | `float16`, `float32`, `float64`   |
| Boolean  | `bool`                            |
| Complex  | `complex64`, `complex128`         |


In [3]:
np.dtype(np.float64).itemsize   # 8 bytes

8

In [4]:
np.dtype(np.float32).itemsize   # 4 bytes

4

### Explicitly Setting dtype

#### At creation time:

In [ ]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [6]:
np.zeros((2, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Casting later (astype)

In [7]:
a = np.array([1, 2, 3])
b = a.astype(np.float32)

`astype()` **always creates a copy.**

### Automatic Type Promotion (Upcasting)
NumPy chooses the smallest common type that can represent all values.

In [8]:
np.array([1, 2, 3.5]).dtype

dtype('float64')

#### Common upcasting rules:
int -> float -> complex

In [9]:
np.array([1, 2, True]).dtype

dtype('int64')

In [10]:
np.array([1, 2.0]).dtype

dtype('float64')

In [11]:
np.array([1, 2 + 3j]).dtype

dtype('complex128')

#### Arithmetic upcasts

In [13]:
a = np.array([1, 2, 3], dtype=np.int32)
b = a + 0.5
b.dtype

dtype('float64')

### NaN, inf, -inf
- Means 'Not a Number'
- Exists **only in floating types**

**Why can’t NumPy store NaN in integer arrays?**

Because:
- NaN is a **floating-point concept (IEEE 754)**
- Integers have no bit-pattern for NaN

This is fundamental to numerical computing.

In [14]:
a = np.array([1, 2, np.nan])
a.dtype

dtype('float64')

In [17]:
print(np.isnan(a))
print(np.isinf(a))
print(np.isfinite(a))


[False False  True]
[False False False]
[ True  True False]


### NaN-Safe Aggregations

In [20]:
print(np.mean([1, 2, np.nan]))

nan


In [21]:
print(np.nanmean([1, 2, np.nan]))  
print(np.nansum([1, 2, np.nan]))    
print(np.nanmax([1, np.nan, 4]))    


1.5
3.0
4.0


### Replacing/Handling NaN Values

#### Replace NaN with values:

In [23]:
a = np.array([1, np.nan, 3])
a[np.isnan(a)] = 0
a

array([1., 0., 3.])

#### Using np.nan_to_num:

In [24]:
np.nan_to_num(a, nan=0, posinf=1e9, neginf=-1e9)


array([1., 0., 3.])

Used heavily in:
- feature engineering
- loss stabilization
- numerical pipelines

### Silent Precision Bugs

In [ ]:
a = np.array([1e20, 1, -1e20])
np.sum(a)

# Expected: 1

np.float64(0.0)

This is **floating-point precision loss.**

### Exercise 1
What will be the dtype?

np.array([1, 2, True])


In [31]:
np.array([1, 2, True]).dtype

dtype('int64')

### Exercise 2
Predict output & dtype:

a = np.array([1, 2, 3], dtype=np.int32)

b = a + 0.1

print(b, b.dtype)


In [32]:
a = np.array([1, 2, 3], dtype=np.int32)
b = a + 0.1
print(b, b.dtype)

[1.1 2.1 3.1] float64


### Exercise 3
Fix the NaN issue:

arr = np.array([10, np.nan, 30])

print(np.mean(arr))


In [34]:
arr = np.array([10, np.nan, 30])
print(np.nanmean(arr))

20.0


### Exercise 4
Convert this array to `float32` **without modifying the original:**

a = np.array([1, 2, 3])


In [38]:
a = np.array([1, 2, 3])
b = a.astype(np.float32)
b

array([1., 2., 3.], dtype=float32)