### Vectorization
Applying an operation to an entire array **without explicit Python loops.**

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a ** 2
print(b)

[ 1  4  9 16]


### Universal Functions (UFuncs)
UFuncs are **vectorized functions** that operate element-wise.

In [2]:
print(np.add(a, 10))
print(np.multiply(a, 2))
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))

[11 12 13 14]
[2 4 6 8]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


### Broadcasting
NumPy does not create expanded copies of arrays; it reuses the same memory and adjusts strides to simulate expansion.

#### Broadcasting Rules:
When operating on two arrays:
1. Compare shapes from right to left
2. Dimensions are compatible if:
    - they are equal, or
    - one of them is 1
3. Result shape = max of each dimension

In [3]:
a = np.array([1, 2, 3])
a + 10

array([11, 12, 13])

In [ ]:
a = np.arange(3).reshape(3,1) # (3, 1)
print(a)
b = np.arange(4) # (1, 4)
print(b)
a + b # (3, 4)


[[0]
 [1]
 [2]]
[0 1 2 3]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [8]:
X = np.array([[10, 20],
              [30, 40],
              [50, 60]])

mean = X.mean(axis=0) # (2,)
std = X.std(axis=0) # (2,)

X_norm = (X - mean) / std
print(X_norm)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


### Exercise 1
Rewrite this using vectorization:

```python
result = []
for x in range(5):
    result.append(x * 3)
```


In [9]:
x = np.arange(5)
x * 3

array([ 0,  3,  6,  9, 12])

### Exercise 2
Predict the result shape:

```python
a = np.zeros((4, 1))
b = np.zeros((5,))
a + b
```

In [ ]:
a = np.zeros((4, 1))
b = np.zeros((5,)) # (1, 5)
a + b # (4, 5)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Exercise 3
Fix the broadcasting error:

```python 
X = np.ones((3, 2))
bias = np.array([1, 2, 3])
X + bias
```

In [13]:
X = np.ones((3, 2))
bias = np.array([1, 2, 3])
bias = bias.reshape((3, 1))
X + bias


array([[2., 2.],
       [3., 3.],
       [4., 4.]])