**Reductions** are the operations that **collapse dimensions:**

`sum`, `mean`, `min`, `max`, etc.

### Basic Reductions (1D)

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4])

np.sum(a)
np.mean(a)    
np.min(a)     
np.max(a)     
np.prod(a) 

np.int64(24)

### Reductions on 2D Arrays

In [ ]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

np.int64(21)

#### Without axis:

In [7]:
np.sum(X)

np.int64(21)

#### axis:
axis tells NumPy which dimension to collapse

**Visual model:**
- `axis=0` → collapse rows → **operate column-wise**
- `axis=1` → collapse columns → **operate row-wise**

In [8]:
X = [[1, 2, 3],
     [4, 5, 6]]

#### `axis=0` (column-wise)

In [10]:
np.sum(X, axis=0) # column-wise

array([5, 7, 9])

#### `axis=1` (row-wise)

In [11]:
np.sum(X, axis=1)

array([ 6, 15])

In [14]:
np.sum(X, axis=0).shape   # (3,)

(3,)

In [15]:

np.sum(X, axis=1).shape   # (2,)

(2,)

#### Keep dimensions

In [17]:
np.sum(X, axis=0, keepdims=True)

array([[5, 7, 9]])

#### argmin/argmax (Indices, not values)
Returns **indices**, not values

In [18]:
a = np.array([10, 50, 20])

print(np.argmax(a))
print(np.argmin(a))

1
0


### Statistical Aggregations

In [20]:
print(np.mean(X, axis=0))
print(np.std(X, axis=0))
print(np.var(X, axis=0))
print(np.median(X, axis=0))
print(np.percentile(X, 50, axis=0))


[2.5 3.5 4.5]
[1.5 1.5 1.5]
[2.25 2.25 2.25]
[2.5 3.5 4.5]
[2.5 3.5 4.5]


In [ ]:
a = np.array([1, 2, 3, 4])

print(np.cumsum(a))    # [1  3  6 10]
print(np.cumprod(a))   # [1  2  6 24]

[ 1  3  6 10]
[ 1  2  6 24]


### NaN-Safe Reductions

In [23]:
arr = np.array([1, np.nan, 3])

print(np.sum(arr))       # nan
print(np.nansum(arr))   # 4
print(np.nanmean(arr))   # 2
print(np.nanmax(arr))   # 3

nan
4.0
2.0
3.0


### Chaining Reductions (ML Pattern)
Example: Mean squared value per row

In [24]:
X = np.array([[1, 2],
              [3, 4]])
np.mean(X**2, axis=1)

array([ 2.5, 12.5])

### Exercise 1
Given:

A = np.array([[1, 2, 3],
              [4, 5, 6]])


Compute:
- sum of each column
- sum of each row

In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

column_sum = np.sum(A, axis=0)
row_sum = np.sum(A, axis=1)

### Exercise 2
What is the output and shape?

np.mean(A, axis=0)

np.mean(A, axis=1)

In [36]:
print(np.mean(A, axis=0))
print(np.mean(A, axis=1))


[2.5 3.5 4.5]
[2. 5.]


### Exercise 3
Using `keepdims=True`, compute column-wise mean of `A`

In [31]:
column_mean = np.mean(A, axis=0, keepdims=True)

### Exercise 4
From this array:

b = np.array([5, 10, 3, 8])

Find:
- max value
- index of max value

In [34]:
b = np.array([5, 10, 3, 8])

print(np.max(b))
print(np.argmax(b))

10
1
