### reshape()
Change Shape without changing Data

In [2]:
import numpy as np

In [3]:
a = np.arange(6) # (6,)
b = a.reshape(2, 3) # (2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

### View vs Copy
`reshape()` usually returns a view

In [4]:
a = np.arange(6)
b = a.reshape(2, 3)
b[0, 0] = 999
print(a)

[999   1   2   3   4   5]


For safety, use `copy()`

In [6]:
a = np.arange(6)
b = a.reshape(2, 3).copy()
b[0, 0] = 999
print(a)

[0 1 2 3 4 5]


### Flattening Arrays

In [8]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

In [9]:
X.ravel()

array([1, 2, 3, 4, 5, 6])

In [10]:
X.flatten()

array([1, 2, 3, 4, 5, 6])

| Method      | Copy?            |
| ----------- | ---------------- |
| `ravel()`   | View if possible |
| `flatten()` | Always copy      |


Use `ravel()` for performance.

### Transpose and Axis Reordering

In [11]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.transpose(X)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Transpose for 3D and Higher

In [13]:
A = np.zeros((2, 3, 4))
A

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
A.shape

(2, 3, 4)

(axis 0, axis 1, axis 2) = (2, 3, 4) = (batch, rows, columns)

In [16]:
B = np.transpose(A, axes=(1, 0, 2))
B

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
B.shape

(3, 2, 4)

- Old axis 1 → new axis 0
- Old axis 0 → new axis 1
- Old axis 2 → stays axis 2

np.transpose(array, axes=(new_order_of_axes))

### swapaxes() & moveaxis()

#### swapaxes()
np.swapaxes(array, axis1, axis2)

In [22]:
A = np.zeros((2, 3, 4))
B = np.swapaxes(A, 0, 1)

print(A.shape)
print(B.shape)

# Equivalent to:
np.transpose(A, axes=(1, 0, 2))

(2, 3, 4)
(3, 2, 4)


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### moveaxis()
np.moveaxis(array, source, destination)

In [24]:
A = np.zeros((2, 3, 4))
B = np.moveaxis(A, 0, -1)
print(A.shape)
print(B.shape)

(2, 3, 4)
(3, 4, 2)


**NOTE:** `transpose`, `swapaxes`, `moveaxis` -> creates views

### Adding and Removing Dimensions

#### Add Dimension

In [29]:
a = np.array([1, 2, 3])
print(a.shape)

print(a[:, np.newaxis]) # (3, 1)
print(a[np.newaxis, :]) # (1, 3)

np.expand_dims(a, axis=1)


(3,)
[[1]
 [2]
 [3]]
[[1 2 3]]


array([[1],
       [2],
       [3]])

#### Remove size-1 dimensions

In [31]:
np.squeeze(a)


array([1, 2, 3])

### Stacking Arrays

#### stack (new dimension)

In [32]:
np.stack([a, a, a], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

#### Vertical/Horizontal

In [34]:
print(np.vstack([a, a]))
print(np.hstack([a, a]))


[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]


### Concatenation
- `stack` -> adds dimension
- `concatenate` -> extends existing one

In [41]:
np.concatenate([a, a], axis=0)


array([1, 2, 3, 1, 2, 3])

In [43]:
print(np.split(a, 3))
print(np.array_split(a, 4))



[array([1]), array([2]), array([3])]
[array([1]), array([2]), array([3]), array([], dtype=int64)]


### Exercise 1
Reshape array [1,2,3,4,5,6] into shape (3, 2).

In [3]:
a = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Exercise 2
Convert a 1D array of shape (5,) into:
- row vector (1, 5)
- column vector (5, 1)

In [8]:
X = np.arange(5)
row_vector = X[np.newaxis, :]
column_vector = X[:, np.newaxis]

### Exercise 3
Given:

```python
X = np.array([[1, 2],
              [3, 4]])
```

Create:
```python
[[1, 2, 1, 2],
 [3, 4, 3, 4]]

```

In [13]:
X = np.array([[1, 2],
              [3, 4]])

X = np.hstack((X, X))
# X = np.concatenate((X, X), axis=1)