### Vectors and Matrices

In [1]:
import numpy as np

In [2]:
v = np.array([1, 2, 3]) # vector (1D)

M = np.array([[1, 2],
              [3, 4]]) # matrix (2D)

Important: 1D arrays are not row/column matrices

### Matrix Multiplication

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [4]:
A @ B

array([[19, 22],
       [43, 50]])

In [5]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [6]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

### Dot Product (Vectors)

In [7]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [8]:
np.dot(u, v)

np.int64(32)

### Vector-Matrix & Matrix-Vector Products

In [9]:
A = np.array([[1, 2],
              [3, 4]])

x = np.array([10, 20])

In [10]:
A @ x

array([ 50, 110])

In [11]:
x @ A

array([ 70, 100])

**x is a 1D vector (shape (2,))**, NumPy handles it very differently than a 2D matrix.

It acts like a **"shapeshifter."** NumPy will automatically treat it as either a row or a column vector depending on where it sits in the multiplication, and the result will always be returned as a 1D array.

### Transpose

In [12]:
A.T

array([[1, 3],
       [2, 4]])

### Norms (Magnitude, Length, Size)
A **norm** measures the size of a vector or matrix.

| Norm | Meaning   |
| ---- | --------- |
| L2   | Euclidean |
| L1   | Manhattan |
| ∞    | Max       |


In [13]:
x = np.array([3, 4])

#### L2 norm (Euclidean distance)

In [14]:
np.linalg.norm(x)

np.float64(5.0)

#### L1 norm (Manhattan distance)

In [15]:
np.linalg.norm(x, ord=1)

np.float64(7.0)

#### Infinity norm (Max absolute value)

In [16]:
np.linalg.norm(x, ord=np.inf)

np.float64(4.0)

### Solving Linear Systems (Ax = b)

#### Bad Approach 
```python
x = np.linalg.inv(A) @ b
```

- expensive
- unstable

#### Correct Approach
```python
x = np.linalg.solve(A, b)
```

In [17]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 10])

np.linalg.solve(A, b)

array([1., 3.])

### Matrix Inverse, Determinant, Rank

In [18]:
print(np.linalg.inv(A))
print(np.linalg.det(A))
print(np.linalg.matrix_rank(A))

[[ 0.6 -0.2]
 [-0.2  0.4]]
5.000000000000001
2


### Eigenvalues & Eigenvectors
**Intuition:**

An **eigenvector** of a matrix `A`:
- does **not change direction**
- only scales

```python
A v = λ v
```

Where:
- `v` -> eigenvector 
- `λ` -> eigenvalue


In [19]:
A = np.array([[2, 0],
              [0, 3]])

eigvals, eigvecs = np.linalg.eig(A)

print(eigvals)
print(eigvecs)


[2. 3.]
[[1. 0.]
 [0. 1.]]


### Singular Value Decomposition(SVD)

Used in:
- dimensionality reduction
- recommender systems
- low-rank approximations

In [20]:
U, S, Vt = np.linalg.svd(A)
print(U)
print(S)
print(Vt)

[[0. 1.]
 [1. 0.]]
[3. 2.]
[[0. 1.]
 [1. 0.]]


### Exercise 1
Compute the matrix multiplication:
```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

```


In [21]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])


print(A @ B)
print(B @ A)

[[ 4  4]
 [10  8]]
[[ 2  4]
 [ 7 10]]


### Exercise 2
Compute dot product of:
```python
u = np.array([1, 3, 5])
v = np.array([2, 4, 6])
```

In [22]:
u = np.array([1, 3, 5])
v = np.array([2, 4, 6])

print(np.dot(u, v))

44


### Exercise 3
Solve the system:
```python
2x + y = 5
x + 3y = 10
```

In [24]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 10])

np.linalg.solve(A, b)

array([1., 3.])

### Exercise 4
Compute the L2 norm of:
```python
x = np.array([6, 8])
```

In [25]:
x = np.array([6, 8])

np.linalg.norm(x)

np.float64(10.0)