### Creating a Random Generator

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(42)

- `42` is the **seed**
- Same seed -> same results (reproducibility)

### Uniform Random Numbers
#### Random floats in [0, 1)

In [3]:
rng.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

#### Random floats in a shape

In [4]:
rng.random((2, 3))

array([[0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802]])

### Random Integers

In [5]:
rng.integers(low=0, high=10, size=5)

array([1, 9, 7, 6, 4])

- `low` inclusive
- `high` exclusive

### Normal (Gaussian) Distribution

In [7]:
rng.normal(loc=0.0, scale=1.0, size=5)

array([ 0.46750934, -0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ])

Parameters:
- `loc` -> mean (μ)
- `scale` -> standard deviation (σ)

Used in:
- weight initialization
- noise injection
- probabilistic models

### Other Useful Distributions

In [8]:
rng.uniform(-1, 1, size=5)

array([ 0.2633288 ,  0.51617548, -0.29094806,  0.94139605,  0.78624224])

In [9]:
rng.exponential(scale=1.0, size=5)

array([0.65579615, 0.41708671, 0.45331969, 0.07707715, 0.17963225])

In [10]:
rng.binomial(n=10, p=0.5, size=5)

array([6, 6, 8, 4, 4])

| Scenario          | Distribution |
| ----------------- | ------------ |
| Random guess      | Uniform      |
| Measurement noise | Normal       |
| Waiting time      | Exponential  |
| Binary outcomes   | Binomial     |
| Event counts      | Poisson      |
| Sampling data     | Choice       |


### Reproducibility

In [11]:
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)

print(rng1.random(5))
print(rng2.random(5))

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


### Shuffling Data
#### Shuffle in-place
Modifies the original array

In [13]:
arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)
arr

array([4, 3, 5, 1, 2])

#### Permutation (safe)
- Returns a shuffled copy
- Original unchanged

In [14]:
rng.permutation(arr)

array([4, 2, 1, 5, 3])

### Train-Test Split

In [17]:
X = np.arange(20).reshape(10, 2)

indices = rng.permutation(len(X))
train_idx = indices[:7]
test_idx = indices[7:]

In [19]:
X_train = X[train_idx]
X_train

array([[ 2,  3],
       [ 6,  7],
       [ 0,  1],
       [ 4,  5],
       [18, 19],
       [12, 13],
       [10, 11]])

In [21]:
X_test = X[test_idx]
X_test

array([[16, 17],
       [14, 15],
       [ 8,  9]])

### Random Choice/Sampling

In [22]:
rng.choice([10, 20, 30], size=5)

array([20, 30, 10, 10, 30])

In [23]:
rng.choice(10, size=5, replace=False)

array([8, 0, 6, 1, 3])

### Testing with Randomness
#### Deterministic test example:

In [28]:
def test_random_output():
    rng = np.random.default_rng(0)
    x = rng.random(3)
    assert np.allclose(x, [0.63696169, 0.26978671, 0.04097352])

### Exercise 1
Create a random generator with seed 123 and generate:
- 5 random floats in [0, 1)
- 5 random integers between 10 and 50

In [34]:
rng = np.random.default_rng(123)
random_float = rng.random(5)
random_integer = rng.integers(10, 50, 5)

### Exercise 2
Generate a (3, 3) matrix from a standard normal distribution.

In [41]:
# rng.normal(size=(3, 3))
x = rng.normal(loc=0.0, scale=1.0, size=(3,3))
x

array([[ 2.28990995, -0.71818115,  0.03260774],
       [ 0.0280499 ,  0.02827212,  0.05534586],
       [-0.48156286, -0.5834075 , -0.8621605 ]])

### Exercise 3
Shuffle this array without modifying the original:
```
arr = np.array([10, 20, 30, 40, 50])
```


In [42]:
arr = np.array([10, 20, 30, 40, 50])
shuffled = rng.permutation(arr)

### Exercise 4
Randomly sample **3 unique values** from `np.arange(10)`.

In [47]:
rng = np.random.default_rng(123)
sample = rng.choice(np.arange(10), size=3, replace=False)
print(sample)

[5 6 0]
