### `np.where()` - Conditional Logic without Loops
```python
np.where(condition, x, y)
```

In [1]:
import numpy as np

In [2]:
a = np.array([1, -2, 3, -4])

np.where(a > 0, a, 0)

array([1, 0, 3, 0])

#### `np.where()` as Index Finder

In [3]:
idx = np.where(a < 0)
idx

(array([1, 3]),)

### Logical Opoerations

In [4]:
mask = np.logical_and(a > 0, a < 5)
a[mask]

array([1, 3])

#### Equivalent Shorthand:

In [5]:
a[(a > 0) & (a < 5)]

array([1, 3])

### `np.take()` - Indexed Reads

In [6]:
a = np.array([10, 20, 30, 40])
np.take(a, [0, 3])

array([10, 40])

### `np.put()` - Indexed Writes

In [8]:
a = np.array([1, 2, 3, 4])
np.put(a, [0, 2], 100)
a

array([100,   2, 100,   4])

### `np.ix_()` - Cartesian Indexing

In [16]:
rows = [0, 2]
cols = [1, 3]

np.ix_(rows, cols)

(array([[0],
        [2]]),
 array([[1, 3]]))

### One-Hot Encoding (NumPy)

In [18]:
labels = np.array([0, 2, 1])
num_classes = 3

one_hot = np.zeros((len(labels), num_classes))
one_hot[np.arange(len(labels)), labels] = 1

one_hot

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

### Binning & Bucketing

In [20]:
values = np.array([10, 25, 35, 60])
bins = np.array([0, 20, 40, 60])

np.digitize(values, bins)

array([1, 2, 2, 4])

### Masked Updates

In [22]:
X = np.array([[1, -1],
              [3, -2]])

X[X < 0] = 0
X

array([[1, 0],
       [3, 0]])

### Exercise 1
Replace negative values with `-1` using `np.where`

In [23]:
a = np.array([3, -2, 5, -7, 0])
result = np.where(a < 0, -1, a)
print(result)

[ 3 -1  5 -1  0]


### Exercise 2
Select rows `[1, 3]` and columns `[0, 2]` using `np.ix_`

In [ ]:
X = np.arange(20).reshape(5, 4)

rows = [1, 3]
cols = [0, 2]

submatrix = X[np.ix_(rows, cols)]
print(submatrix)

[[ 4  6]
 [12 14]]


### Exercise 3
Create one-hot encoding for:
```python
labels = np.array([1, 0, 2, 1])
num_classes = 3
```

In [25]:
labels = np.array([1, 0, 2, 1])
num_classes = 3

one_hot = np.zeros((len(labels), num_classes), dtype=int)
one_hot[np.arange(len(labels)), labels] = 1

print(one_hot)

[[0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]]


### Exercise 4
Bin this array using bins `[0, 10, 20, 30]`:
```python
x = np.array([5, 15, 25])
```

In [26]:
x = np.array([5, 15, 25])
bins = np.array([0, 10, 20, 30])

binned = np.digitize(x, bins)
print(binned)

[1 2 3]
