### What is Clustering?
Clustering is:
> Grouping similar data points together.

Unlike classification:
```
Classification
→ Labels exist
```
Example:
```
Dog
Cat
Bird
```
In clustering:
```
Labels do not exist
```
The algorithm discovers groups automatically.

### Real-World Example
Suppose an e-commerce company has:
| Customer | Income | Spending |
| -------- | ------ | -------- |
| A        | 30k    | Low      |
| B        | 35k    | Low      |
| C        | 120k   | High     |
| D        | 150k   | High     |

No labels.

Goal:
```
Find customer groups
```
Possible result:
```
Cluster 1 → Budget Customers
Cluster 2 → Premium Customers
```

### What is K-Means?
K-Means tries to partition data into:
$$
K
$$
clusters.

Where:
$$
K = number of clusters
$$
chosen beforehand.

Example:
$$
K = 3
$$
Means:
$$
Find \ 3 \ groups
$$

### Core Idea
Each cluster has: **Centroid**

A centroid is:
> The average position of all points in a cluster.

Example:

Points:
```
(2,2)
(3,2)
(4,2)
```
Centroid:
$$
(\frac{2 + 3 + 4}{3}, \frac{2 + 2 + 2}{3}) = (3, 2)
$$

### Optimization Goal
K-Means minimizes: **Within Cluster Sum of Squares (WCSS)**

Also called:
- Inertia
- SSE (Sum of Squared Errors)

Formula:
$$
J = \sum_{i=1}^{K} \sum_{x \in C_i} \|x - \mu_i\|^2
$$

where:
- $C_i$ = cluster $i$
- $\mu_i$ = centroid of cluster $i$
- $||x - \mu_i||^2$ = squared Euclidean distance between data point $x$ and centroid $\mu_i$

### Interpretation
Goal:
```
Points inside cluster
should be close together
```

### K-Means Algorithm
#### Step 1
Choose:
$$
K
$$
centroids randomly.

#### Step 2
Assign each point to nearest centroid.

#### Step 3
Recompute centroids.

#### Step 4
Repeat until convergence.

### Example Walkthrough
Suppose:
```
Points:
(1,1)
(2,1)
(8,8)
(9,8)
```
Choose:
```
K = 2
```

#### Initial Centroids
```
C1 = (1,1)
C2 = (8,8)
```

#### Assignment
Points nearest C1:
```
(1,1)
(2,1)
```
Points nearest C2:
```
(8,8)
(9,8)
```

#### Update Centroids
Cluster 1:
$$
(1.5,1)
$$
Cluster 2:
$$
(8.5,8)
$$
Repeat.

Eventually clusters stabilize.

### Distance Metric
Typically:
#### Euclidean Distance
$$
d(x,y) = \sqrt{\sum_{i=1}^{n}(x_i - y_i)^2}
$$

Example:

Points:
```
A=(1,1)
B=(4,5)
```
Distance:
$$
d(A,B) = \sqrt{(4-1)^2 + (5-1)^2} = 5
$$

### Why Scaling is Critical
Suppose:
| Feature | Range   |
| ------- | ------- |
| Age     | 20–60   |
| Income  | 20k–20L |

Income dominates distance.

Clusters become meaningless.

**Always Scale Before K-Means**

Typically:
```
StandardScaler
```

### Convergence

K-Means stops when:
#### Condition 1
No cluster changes.

OR

#### Condition 2
Centroids stop moving.

OR

#### Condition 3
Maximum iterations reached.

Mathematically:
$$
\mu_{old} ≈ \mu_{new}
$$

### Complexity
For:
- N samples
- K clusters
- I iterations

Complexity:
$$
O(NKI)
$$
Usually efficient.

### Local Minima Problem
Important:

K-Means does NOT guarantee: **Global optimum**

Only: **Local optimum**

Different initial centroids: **Different results**

### K-Means++
**K-Means++** is the solution to **Local Minima Problem**

Procedure:
- Pick first centroid randomly.
- Pick next centroid far from existing ones.
- Repeat.

Benefits:
- Faster convergence
- Better clusters

Used by default in Scikit-Learn.


In [3]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Sample dataset
X = np.array([
    [1, 2],
    [1, 4],
    [1, 0],
    [10, 2],
    [10, 4],
    [10, 0]
])

# Scale data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize K-Means
kmeans = KMeans(
    n_clusters=3,
    init="k-means++",
    n_init=10,
    random_state=42
)

# Train model
kmeans.fit(X_scaled)

# Get results
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Convert centroids back to original scale
original_centroids = scaler.inverse_transform(centroids)

print("Cluster Labels:")
print(labels)

print("\nCluster Centroids (Scaled):")
print(centroids)

print("\nCluster Centroids (Original Scale):")
print(original_centroids)

print(kmeans.inertia_)

Cluster Labels:
[0 0 1 2 2 1]

Cluster Centroids (Scaled):
[[-1.          0.61237244]
 [ 0.         -1.22474487]
 [ 1.          0.61237244]]

Cluster Centroids (Original Scale):
[[1.00000000e+00 3.00000000e+00]
 [5.50000000e+00 2.22044605e-16]
 [1.00000000e+01 3.00000000e+00]]
3.5


### Understanding Output
#### labels_
Cluster assignment.

Example:
```
[0,0,1,1,2,2]
```

#### cluster_centers_
Centroids.

#### inertia_
WCSS value.
```python
print(kmeans.inertia_)
```
Lower is better.

### Advantages
- Simple
- Fast
- Scalable
- Easy interpretation

### Limitations
- Need K beforehand
- Sensitive to outliers
- Assumes spherical clusters
- Sensitive to initialization
- Not suitable for arbitrary shapes

### Failure Example
Suppose data forms:
```
Two concentric circles
```
K-Means fails.

Because:

Distance-to-centroid assumption breaks.

DBSCAN will solve this.